// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0vJk-PSqgpUsT4owCrdp6q0jX9BlAGQ',
    appId: '1:1060194918769:web:9c2970b96a8ad029af16d0',
    messagingSenderId: '1060194918769',
    projectId: 'qryptic-7c567',
    authDomain: 'qryptic-7c567.firebaseapp.com',
    storageBucket: 'qryptic-7c567.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBTU4BeU9kDXEev1sOgJ0CRKulrN_vqU',
    appId: '1:1060194918769:android:74009e1b9cde2f03af16d0',
    messagingSenderId: '1060194918769',
    projectId: 'qryptic-7c567',
    storageBucket: 'qryptic-7c567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb86IZfOqwpHAOFNVSQw93oFIchelQCnA',
    appId: '1:1060194918769:ios:627f3023f0bffdc2af16d0',
    messagingSenderId: '1060194918769',
    projectId: 'qryptic-7c567',
    storageBucket: 'qryptic-7c567.firebasestorage.app',
    iosBundleId: 'com.example.qryptic',
  );
}
